#
# This file contains specific versions of subscriptions for OpenShift 4.11
#
clusterGroup:
  subscriptions:      
    seldon-dev:
      name: seldon-operator
      namespace: manuela-tst-all
      channel: stable
      source: community-operators

 # TODO: Allow namespace to be a list
    amqstreams-dev:
      name: amq-streams
      namespace: manuela-tst-all
      channel: stable
      
    camelk-dev:
      name: red-hat-camel-k
      namespace: manuela-tst-all
      channel: stable

