global:
  datacenter:
    clustername: datacenter-XXXXX
    domain: BASEDOMAIN

  s3:
    bucket:
      name: BUCKETNAME
      region: us-west-1
      message:
        aggregation:
          count: 100
      custom:
        endpoint:
          enabled: true

kafka:
  broker:
    uri: "manuela-data-lake-kafka-bootstrap.manuela-data-lake.svc:9092"
    topic:
      temperature: "iot-sensor-sw-temperature"
      vibration: "iot-sensor-sw-vibration"

